-- Backfill capacity columns on legacy model_record_t rows where (model_factory,
-- model_name) matches a W1 day-one catalog entry. Idempotent: only writes when
-- context_window_tokens IS NULL, so re-running on already-backfilled rows is a
-- no-op.
--
-- Why this migration exists: W1 step 7 made context_window_tokens and
-- max_output_tokens required at the frontend Add/Edit forms, but pre-existing
-- model_record_t rows from older deployments still have NULL capacity columns.
-- Without these values, W1 ModelCapacityResolver returns provider_capability_unknown
-- and W2 produces no SafeInputBudgetSnapshot, which silently disables CM-030
-- output-cap enforcement at dispatch.
--
-- Catalog source of truth: backend/consts/capability_profiles.py (W1 ADR
-- Decision 1). If the catalog is bumped, mirror the change here in a new
-- migration; do not edit this file in place.
--
-- Coverage caveat: rows whose model_factory does not match a catalog provider
-- key (commonly the manual-add default 'OpenAI-API-Compatible' per CM-031)
-- will not be backfilled by this migration. Operators must either update
-- model_factory directly, re-save the model through the W1-aware UI, or wait
-- for W17. Startup logs surface the residual count.

DO $$
DECLARE
    v_updated INTEGER := 0;
    v_total   INTEGER := 0;
BEGIN
    -- openai/gpt-4o
    UPDATE nexent.model_record_t
       SET context_window_tokens = 128000,
           max_output_tokens = 16384,
           default_output_reserve_tokens = 4096
     WHERE LOWER(model_factory) = 'openai'
       AND model_name = 'gpt-4o'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- openai/gpt-4.1
    UPDATE nexent.model_record_t
       SET context_window_tokens = 1000000,
           max_output_tokens = 32768,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'openai'
       AND model_name = 'gpt-4.1'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- dashscope/qwen-plus
    UPDATE nexent.model_record_t
       SET context_window_tokens = 131072,
           max_output_tokens = 16384,
           default_output_reserve_tokens = 4096
     WHERE LOWER(model_factory) = 'dashscope'
       AND model_name = 'qwen-plus'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- dashscope/qwen-turbo
    UPDATE nexent.model_record_t
       SET context_window_tokens = 1000000,
           max_output_tokens = 16384,
           default_output_reserve_tokens = 4096
     WHERE LOWER(model_factory) = 'dashscope'
       AND model_name = 'qwen-turbo'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- dashscope/glm-5.1
    UPDATE nexent.model_record_t
       SET context_window_tokens = 200000,
           max_output_tokens = 131072,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'dashscope'
       AND model_name = 'glm-5.1'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- silicon/Qwen/Qwen3.6-27B
    UPDATE nexent.model_record_t
       SET context_window_tokens = 262144,
           max_output_tokens = 65536,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'silicon'
       AND model_name = 'Qwen/Qwen3.6-27B'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- silicon/Pro/moonshotai/Kimi-K2.6
    UPDATE nexent.model_record_t
       SET context_window_tokens = 262144,
           max_output_tokens = 131072,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'silicon'
       AND model_name = 'Pro/moonshotai/Kimi-K2.6'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    RAISE NOTICE 'W2 catalog backfill: % row(s) updated', v_total;
END $$;
