"""Transactional initialization of NL2AGENT draft sessions."""

import logging
from dataclasses import dataclass
from typing import Any, Awaitable, Callable, Dict, List, Optional

from consts.exceptions import AgentRunException

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SessionInitializationDependencies:
    """Database, Redis, and catalog operations required to start a session."""

    search_agent_id_by_name: Callable[..., int]
    search_agent_info_by_id: Callable[..., Optional[Dict[str, Any]]]
    ensure_seed_defaults: Callable[..., Any]
    load_session_catalogs: Callable[
        [str],
        Awaitable[tuple[Dict[str, List[Dict[str, Any]]], List[str]]],
    ]
    get_db_session: Callable[..., Any]
    create_agent: Callable[..., Dict[str, Any]]
    create_conversation: Callable[..., Dict[str, Any]]
    initialize_session_state: Callable[..., Any]
    set_session_catalogs: Callable[..., Any]
    delete_session_catalogs: Callable[..., Any]
    new_uuid: Callable[..., Any]
    builder_agent_name: str
    draft_name_prefix: str


async def start_session(
    dependencies: SessionInitializationDependencies,
    *,
    user_id: str,
    tenant_id: str,
    language: str,
) -> Dict[str, Any]:
    """Create a draft and Conversation, then atomically hand off Redis state."""
    del language
    try:
        builder_agent_id = dependencies.search_agent_id_by_name(
            dependencies.builder_agent_name,
            tenant_id,
        )
    except ValueError as exc:
        if str(exc) != "agent not found":
            raise
        raise AgentRunException(
            "NL2AGENT default agent is not initialized. Restart the config service first."
        ) from exc

    try:
        builder_agent = dependencies.search_agent_info_by_id(
            agent_id=builder_agent_id,
            tenant_id=tenant_id,
        )
        if builder_agent:
            dependencies.ensure_seed_defaults(
                builder_agent,
                user_id=user_id,
                tenant_id=tenant_id,
            )
    except Exception as exc:
        logger.warning(
            "Failed to verify NL2AGENT prompt template link for tenant %s: %s",
            tenant_id,
            exc,
        )

    draft_name = f"{dependencies.draft_name_prefix}{dependencies.new_uuid().hex[:8]}"
    agent_payload = {
        "name": draft_name,
        "display_name": "Draft Agent (NL2AGENT)",
        "description": "Draft agent generated by NL2AGENT session",
        "max_steps": 15,
        "enabled": True,
        "is_new": False,
    }
    session_catalogs, resource_missing_names = await dependencies.load_session_catalogs(
        tenant_id
    )
    draft_agent_id: Optional[int] = None
    conversation_id: Optional[int] = None
    try:
        with dependencies.get_db_session() as db_session:
            created = dependencies.create_agent(
                agent_payload,
                tenant_id=tenant_id,
                user_id=user_id,
                db_session=db_session,
            )
            draft_agent_id = created.get("agent_id")
            if not isinstance(draft_agent_id, int) or draft_agent_id <= 0:
                raise AgentRunException("Draft agent creation returned no agent_id.")

            conversation = dependencies.create_conversation(
                conversation_title=f"NL2AGENT - {draft_name}",
                user_id=user_id,
                db_session=db_session,
            )
            conversation_id = conversation.get("conversation_id")
            if not isinstance(conversation_id, int) or conversation_id <= 0:
                raise AgentRunException(
                    "Conversation creation returned no conversation_id."
                )

            dependencies.initialize_session_state(
                tenant_id,
                draft_agent_id,
                conversation_id=conversation_id,
            )
            dependencies.set_session_catalogs(
                tenant_id,
                draft_agent_id,
                session_catalogs,
            )
    except Exception as exc:
        if draft_agent_id:
            try:
                dependencies.delete_session_catalogs(
                    tenant_id,
                    draft_agent_id,
                )
            except Exception:
                logger.exception(
                    "Failed to compensate NL2AGENT Redis initialization: "
                    "tenant_id=%s draft_agent_id=%s",
                    tenant_id,
                    draft_agent_id,
                )
        if isinstance(exc, AgentRunException):
            raise
        logger.exception(
            "Failed to initialize NL2AGENT session for tenant_id=%s",
            tenant_id,
        )
        raise AgentRunException("Failed to initialize NL2AGENT session.") from exc

    if resource_missing_names:
        logger.warning(
            "Excluded resource-missing official Skills from NL2AGENT search: "
            "tenant_id=%s draft_agent_id=%s skills=%s",
            tenant_id,
            draft_agent_id,
            resource_missing_names,
        )

    return {
        "nl2agent_agent_id": builder_agent_id,
        "draft_agent_id": draft_agent_id,
        "conversation_id": conversation_id,
        "draft_name": draft_name,
    }
