sonar.projectKey=ModelEngine-Group_nexent
sonar.organization=modelengine-group

sonar.exclusions=**/init.sql,**/migrations/*.sql,**/docker/sql/*.sql
sonar.cpd.exclusions=**/init.sql,**/migrations/*.sql,**/docker/sql/*.sql