{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexent-nginx-config
  namespace: {{ .Values.global.namespace }}
data:
  default.conf: |
{{ (.Values.config | replace "$server_port" (printf "%v" .Values.services.nginx.entryPort | default .Values.services.nginx.nodePort)) | indent 4 }}
{{- end }}
