x-es-vars: &es-vars
  ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
x-minio-vars: &minio-vars
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
  MINIO_REGION: ${MINIO_REGION}
  MINIO_DEFAULT_BUCKET: ${MINIO_DEFAULT_BUCKET}

services:
  nexent-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    container_name: nexent-elasticsearch
    environment:
      <<: *es-vars
      # 单节点模式
      discovery.type: single-node
      # 禁用安全认证（此处与原配置 xpack.security.enabled 矛盾，根据新配置以启用为准）
      # xpack.security.enabled 已启用
      xpack.security.enabled: "true"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      # JVM 内存配置
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      # Elasticsearch 节点名称
      node.name: es01
      # 是否锁定内存
      bootstrap.memory_lock: "false"
      # 磁盘低水位线
      cluster.routing.allocation.disk.watermark.low: "5gb"
      # 磁盘高水位线
      cluster.routing.allocation.disk.watermark.high: "3gb"
      # 磁盘洪水水位线
      cluster.routing.allocation.disk.watermark.flood_stage: "2gb"
      # 时区设置
      TZ: "Asia/Shanghai"
    volumes:
      - $ROOT_DIR/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9210:9200"  # HTTP API
      - "9310:9300"  # 集群通信端口
    networks:
      - nexent
    restart: always  # 一直重启策略
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u elastic:${ELASTIC_PASSWORD} -k http://localhost:9200/_cluster/health | grep -qE '\"status\":\"(green|yellow)\"' || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 20
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志文件最大 100MB
        max-file: "3"  # 最多保留 3 个日志文件

  nexent-postgresql:
    image: postgres:15-alpine
    container_name: nexent-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Asia/Shanghai"
    volumes:
      - ${ROOT_DIR}/postgresql/data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    security_opt:
      - seccomp:unconfined
    restart: always  # 一直重启策略
    logging:
      driver: "json-file"
      options:
        max-size: "100m"  # 单个日志文件最大 100MB
        max-file: "3"  # 最多保留 3 个日志文件
    networks:
      - nexent

  nexent:
    image: nexent/nexent:0.1.0
    container_name: nexent
    command: bash
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - $ROOT_DIR/uploads:/opt/backend/uploads:rw
    environment:
      <<: [*minio-vars, *es-vars]
      skip_proxy: "true"
      UPLOAD_FOLDER: /opt/backend/uploads
      UMASK: 0022
    env_file:
      - .env
    user: root
    depends_on:
      nexent-elasticsearch:
        condition: service_healthy  # 确保 Key 已生成
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - nexent

  nexent-data-process:
    image: nexent/nexent-data-process:0.1.0
    container_name: nexent-data-process
    command: bash
    restart: always
    privileged: true
    ports:
      - "5012:5012"
    volumes:
      - $ROOT_DIR/uploads:/opt/backend/uploads:rw
    environment:
      skip_proxy: "true"
    env_file:
      - .env
    depends_on:
      nexent-elasticsearch:
        condition: service_healthy  # 确保 Key 已生成
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - nexent
    entrypoint: >
      /bin/sh -c "
        python /opt/backend/data_process_service.py || (cd /opt/backend && OPENBLAS_NUM_THREADS=1 UVICORN_LOOP=asyncio uvicorn data_process_service:app --host 0.0.0.0 --port 5012)
      "

  nexent-minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: nexent-minio
    command: server /data
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      <<: *minio-vars
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      TZ: "Asia/Shanghai"
    volumes:
      - $ROOT_DIR/minio/data:/data
    networks:
      - nexent
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    entrypoint: >
      /bin/sh -c "
        minio server /etc/minio/data --address ':9000' --console-address ':9001' &
        MINIO_PID=$$!
        sleep 3
        mc alias set myadmin http://localhost:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
        mc admin user add myadmin $MINIO_ACCESS_KEY $MINIO_SECRET_KEY
        # 添加权限
        mc admin policy attach myadmin readwrite --user=$MINIO_ACCESS_KEY
        mc mb myadmin/$MINIO_DEFAULT_BUCKET
        mc anonymous set download myadmin/$MINIO_DEFAULT_BUCKET
        wait $$MINIO_PID
      "

networks:
  nexent:
    driver: bridge

