"""Default-free configuration constants for the standalone AIDP adapter."""

AIDP_BASE_URL = ""
AIDP_API_KEY = ""
AIDP_TENANT_ID = ""

DEFAULT_CHUNK_TOKEN_NUM = 1024
DEFAULT_CHUNK_OVERLAP_NUM = 128
DEFAULT_IS_PERSONAL = 0
DEFAULT_CAPTION_ENABLE = 0
DEFAULT_EMBEDDING_MODEL = "default"
DEFAULT_VLM_MODEL = ""
DEFAULT_TOP_K = 10
DEFAULT_SIMILARITY = 0.0
DEFAULT_SMARTSPLIT = 1

ADAPTER_PLATFORM = "aidp"
ADAPTER_VERSION = "1.0.0"
COUNT_PATH_KDS_ID = "0"
