from datetime import datetime, timedelta, timezone
from zoneinfo import ZoneInfo

try:
    from croniter import croniter
except ImportError:  # pragma: no cover - dependency fallback for isolated tests
    croniter = None

from .models import ScheduleMode, ScheduleRuleType, ScheduleTrigger


def _ensure_aware(value: datetime, timezone_name: str) -> datetime:
    zone = ZoneInfo(timezone_name)
    if value.tzinfo is None:
        return value.replace(tzinfo=zone)
    return value.astimezone(zone)


def compute_next_fire_at(
    trigger: ScheduleTrigger,
    after: datetime,
    fire_count: int,
) -> datetime | None:
    """Compute the next fire time for both one-shot and recurring schedules."""
    local_after = _ensure_aware(after, trigger.timezone)
    start_at = _ensure_aware(trigger.start_at, trigger.timezone)
    end_at = _ensure_aware(trigger.end_at, trigger.timezone) if trigger.end_at else None

    if trigger.max_fire_count is not None and fire_count >= trigger.max_fire_count:
        return None

    if trigger.mode == ScheduleMode.ONCE:
        if fire_count > 0:
            return None
        next_fire = start_at if start_at >= local_after else local_after
    elif trigger.rule_type == ScheduleRuleType.INTERVAL:
        if local_after <= start_at:
            next_fire = start_at
        else:
            elapsed = (local_after - start_at).total_seconds()
            steps = int(elapsed // trigger.interval_seconds) + 1
            next_fire = start_at + timedelta(seconds=steps * trigger.interval_seconds)
    elif trigger.rule_type == ScheduleRuleType.CRON:
        base = max(local_after, start_at)
        if local_after <= start_at and _cron_matches_start(trigger.cron_expr, start_at):
            next_fire = start_at
        elif croniter is not None:
            next_fire = croniter(trigger.cron_expr, base).get_next(datetime)
            if next_fire < start_at:
                next_fire = croniter(trigger.cron_expr, start_at).get_next(datetime)
        else:
            next_fire = _fallback_next_cron(trigger.cron_expr, base)
    else:
        raise ValueError(f"Unsupported schedule combination: {trigger.mode}/{trigger.rule_type}")

    if end_at and next_fire > end_at:
        return None
    return next_fire.astimezone(timezone.utc)


def _cron_matches_start(expr: str, start_at: datetime) -> bool:
    parts = (expr or "").split()
    if len(parts) != 5:
        if croniter is not None:
            try:
                return croniter.match(expr, start_at)
            except Exception:
                return False
        return False

    minute, hour, day_of_month, month, day_of_week = parts
    checks = (
        _cron_field_matches(minute, start_at.minute),
        _cron_field_matches(hour, start_at.hour),
        _cron_field_matches(day_of_month, start_at.day),
        _cron_field_matches(month, start_at.month),
        _cron_weekday_matches(day_of_week, start_at),
    )
    return all(checks)


def _cron_field_matches(field: str, value: int) -> bool:
    return field == "*" or (field.isdigit() and int(field) == value)


def _cron_weekday_matches(field: str, value: datetime) -> bool:
    if field == "*":
        return True
    if not field.isdigit():
        return False
    return (int(field) - 1) % 7 == value.weekday()


def _fallback_next_cron(expr: str, base: datetime) -> datetime:
    """Fallback for simple five-field cron expressions generated by v1 UI."""
    parts = (expr or "").split()
    if len(parts) != 5:
        raise ValueError("croniter is required for complex cron expressions")
    minute, hour, day_of_month, month, day_of_week = parts
    if not minute.isdigit() or not hour.isdigit():
        raise ValueError("croniter is required for non-numeric minute/hour cron expressions")
    target = base.replace(hour=int(hour), minute=int(minute), second=0, microsecond=0)
    if target <= base:
        target += timedelta(days=1)
    for _ in range(366 * 5):
        if (
            _cron_field_matches(day_of_month, target.day)
            and _cron_field_matches(month, target.month)
            and _cron_weekday_matches(day_of_week, target)
        ):
            return target
        target += timedelta(days=1)
    raise ValueError("Unable to find the next fire time for cron expression")
