-- Migration kind: RECOMMENDED_DATA_FIX
-- Required for: upgraded deployments with existing model_record_t rows.
-- Safe to skip when: fresh deployment, or operators will manually fill capacity fields.
-- Reason: improves legacy model capacity completeness and reconciles the temporary max_tokens alias.
--
-- ------------------------------------------------------------
-- Pre-run self-check (recommended before applying)
-- ------------------------------------------------------------
-- The reconcile block at the bottom of this file rewrites `max_tokens` to
-- match the freshly backfilled `max_output_tokens`. If an operator
-- previously tightened `max_tokens` below the catalog value on a row this
-- migration touches (cost control, prompt-budget caps, etc.), that tighter
-- value will be overwritten with the catalog value.
--
-- Run this query first to surface any such rows:
--
--   SELECT model_id, model_name, model_factory, max_tokens, max_output_tokens
--     FROM nexent.model_record_t
--    WHERE delete_flag = 'N'
--      AND max_tokens IS NOT NULL
--      AND (
--        (LOWER(model_factory)='openai'    AND model_name IN ('gpt-4o','gpt-4.1'))
--        OR (LOWER(model_factory)='dashscope' AND model_name IN ('qwen-plus','qwen-turbo','qwen3.7-max','glm-5.1'))
--        OR (LOWER(model_factory)='silicon'  AND model_name IN ('Qwen/Qwen3.6-27B','Pro/moonshotai/Kimi-K2.6'))
--        OR (LOWER(model_factory)='deepseek' AND model_name IN ('deepseek-v4-flash','deepseek-v4-pro'))
--      );
--
-- If the result is empty: safe to apply the whole file.
-- If the result has rows the operator deliberately tightened: run only the
-- first `DO $$` block (catalog backfill) and skip the second (reconcile),
-- or back up the affected rows before applying.

-- ============================================================
-- Backfill capacity columns on legacy model_record_t rows
-- ============================================================
-- Matches (model_factory, model_name) against W1 day-one catalog entries.
-- Idempotent: only writes when context_window_tokens IS NULL, so re-running on
-- already-backfilled rows is a no-op.
--
-- Catalog source of truth: backend/consts/capability_profiles.py (W1 ADR
-- Decision 1). If the catalog is bumped, mirror the change here in a new
-- migration; do not edit this file in place after it has been released.
--
-- Coverage caveat: rows whose model_factory does not match a catalog provider
-- key (commonly the manual-add default 'OpenAI-API-Compatible' per CM-031)
-- will not be backfilled by this migration. Operators must either update
-- model_factory directly, re-save the model through the W1-aware UI, or wait
-- for W17. Startup logs surface the residual count.

DO $$
DECLARE
    v_updated INTEGER := 0;
    v_total   INTEGER := 0;
BEGIN
    -- openai/gpt-4o
    UPDATE nexent.model_record_t
       SET context_window_tokens = 128000,
           max_output_tokens = 16384,
           default_output_reserve_tokens = 4096
     WHERE LOWER(model_factory) = 'openai'
       AND model_name = 'gpt-4o'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- openai/gpt-4.1
    UPDATE nexent.model_record_t
       SET context_window_tokens = 1000000,
           max_output_tokens = 32768,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'openai'
       AND model_name = 'gpt-4.1'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- dashscope/qwen-plus
    UPDATE nexent.model_record_t
       SET context_window_tokens = 131072,
           max_output_tokens = 16384,
           default_output_reserve_tokens = 4096
     WHERE LOWER(model_factory) = 'dashscope'
       AND model_name = 'qwen-plus'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- dashscope/qwen-turbo
    UPDATE nexent.model_record_t
       SET context_window_tokens = 1000000,
           max_output_tokens = 16384,
           default_output_reserve_tokens = 4096
     WHERE LOWER(model_factory) = 'dashscope'
       AND model_name = 'qwen-turbo'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- dashscope/qwen3.7-max
    UPDATE nexent.model_record_t
       SET context_window_tokens = 1000000,
           max_output_tokens = 65536,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'dashscope'
       AND model_name = 'qwen3.7-max'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- dashscope/glm-5.1
    UPDATE nexent.model_record_t
       SET context_window_tokens = 200000,
           max_output_tokens = 131072,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'dashscope'
       AND model_name = 'glm-5.1'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- silicon/Qwen/Qwen3.6-27B
    UPDATE nexent.model_record_t
       SET context_window_tokens = 262144,
           max_output_tokens = 65536,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'silicon'
       AND model_name = 'Qwen/Qwen3.6-27B'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- silicon/Pro/moonshotai/Kimi-K2.6
    UPDATE nexent.model_record_t
       SET context_window_tokens = 262144,
           max_output_tokens = 131072,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'silicon'
       AND model_name = 'Pro/moonshotai/Kimi-K2.6'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- deepseek/deepseek-v4-flash
    -- (deepseek-chat / deepseek-reasoner intentionally omitted: they alias to
    -- v4-flash and are scheduled for deprecation at 2026-07-24, and pre-W1
    -- deployments may have legacy max_tokens values for those names that
    -- this backfill should not clobber.)
    UPDATE nexent.model_record_t
       SET context_window_tokens = 1000000,
           max_output_tokens = 384000,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'deepseek'
       AND model_name = 'deepseek-v4-flash'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    -- deepseek/deepseek-v4-pro
    UPDATE nexent.model_record_t
       SET context_window_tokens = 1000000,
           max_output_tokens = 384000,
           default_output_reserve_tokens = 8192
     WHERE LOWER(model_factory) = 'deepseek'
       AND model_name = 'deepseek-v4-pro'
       AND delete_flag = 'N'
       AND context_window_tokens IS NULL;
    GET DIAGNOSTICS v_updated = ROW_COUNT;
    v_total := v_total + v_updated;

    RAISE NOTICE 'W2 catalog backfill: % row(s) updated', v_total;
END $$;

-- ============================================================
-- Reconcile the legacy max_tokens column with max_output_tokens
-- ============================================================
-- Runs after the catalog backfill above because the backfill writes
-- max_output_tokens. Scope and safety:
--   * Only touches rows where max_output_tokens IS NOT NULL.
--   * Skips embedding rows because they reuse max_tokens as the vector dimension.
--   * Only updates rows where the two columns actually disagree.
--   * delete_flag = 'N' so soft-deleted rows are left alone.

DO $$
DECLARE
    v_updated INTEGER := 0;
BEGIN
    UPDATE nexent.model_record_t
       SET max_tokens = max_output_tokens
     WHERE delete_flag = 'N'
       AND max_output_tokens IS NOT NULL
       AND COALESCE(max_tokens, -1) <> max_output_tokens
       AND COALESCE(model_type, '') NOT IN ('embedding', 'multi_embedding');

    GET DIAGNOSTICS v_updated = ROW_COUNT;
    RAISE NOTICE 'max_tokens alias reconcile: % row(s) updated', v_updated;
END $$;
