#!/usr/bin/env python3
"""Generate idempotent backfill SQL from capability_profiles.CATALOG.

Usage:
    python scripts/generate_backfill_sql.py > docker/sql/v2.2.x_MMDD_backfill_from_catalog.sql

Run whenever capability_profiles.py changes, then commit the generated SQL.
"""
import sys
import os
import types
from datetime import date
from collections import namedtuple

_project_root = os.path.join(os.path.dirname(__file__), "..")
sys.path.insert(0, os.path.join(_project_root, "backend"))

# Stub SDK types to avoid pulling in the full nexent SDK dependency chain
_nexent_stub = types.ModuleType("nexent")
_nexent_core = types.ModuleType("nexent.core")
_nexent_models = types.ModuleType("nexent.core.models")
_nexent_resolver = types.ModuleType("nexent.core.models.capacity_resolver")

ProfileKey = tuple

class CapabilityProfile:
    """Minimal stub that accepts any keyword arguments."""
    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

_nexent_resolver.ProfileKey = ProfileKey
_nexent_resolver.CapabilityProfile = CapabilityProfile
sys.modules["nexent"] = _nexent_stub
sys.modules["nexent.core"] = _nexent_core
sys.modules["nexent.core.models"] = _nexent_models
sys.modules["nexent.core.models.capacity_resolver"] = _nexent_resolver

from consts.capability_profiles import CATALOG, CATALOG_REVISION

DEFAULT_CONTEXT_WINDOW = 32_768
DEFAULT_MAX_OUTPUT = 4_096
DEFAULT_RESERVE = 4_096


def _sql_int(value: int) -> str:
    return str(value)


def _sql_str(value: str) -> str:
    return value.replace("'", "''")


def main() -> None:
    today = date.today().strftime("%Y-%m-%d")
    lines: list[str] = []

    lines.append(f"-- Generated by scripts/generate_backfill_sql.py on {today}")
    lines.append(f"-- Catalog revision: {CATALOG_REVISION}")
    lines.append(f"-- Catalog entries: {len(CATALOG)}")
    lines.append("--")
    lines.append("-- Migration kind: RECOMMENDED_DATA_FIX")
    lines.append("-- Idempotent: COALESCE protects existing non-NULL values.")
    lines.append("-- Safe: enforces max_output < context_window via GREATEST/LEAST.")
    lines.append("--")
    lines.append("-- Pre-run self-check:")
    lines.append("--")
    lines.append("--   SELECT model_id, model_name, model_factory,")
    lines.append("--          context_window_tokens, max_output_tokens")
    lines.append("--     FROM nexent.model_record_t")
    lines.append("--    WHERE delete_flag = 'N'")
    lines.append("--      AND COALESCE(model_type, 'llm') IN ('llm', 'vlm')")
    lines.append("--      AND (context_window_tokens IS NULL OR max_output_tokens IS NULL);")
    lines.append("--")
    lines.append("-- If the result is empty, this migration is a no-op.")
    lines.append("")

    # Phase 1: catalog-driven backfill
    lines.append("-- ============================================================")
    lines.append("-- Phase 1: Backfill rows matching approved catalog entries")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("    v_total   INTEGER := 0;")
    lines.append("BEGIN")

    from collections import defaultdict
    by_provider: dict[str, list] = defaultdict(list)
    for (provider, model_name), profile in CATALOG.items():
        by_provider[provider].append((model_name, profile))

    for provider in sorted(by_provider.keys()):
        entries = by_provider[provider]
        lines.append(f"    -- {provider} ({len(entries)} entries)")
        for model_name, profile in entries:
            ctx = profile.context_window_tokens
            mout = profile.max_output_tokens
            reserve = profile.default_output_reserve_tokens
            version = _sql_str(profile.capability_profile_version)
            escaped_model = _sql_str(model_name)

            lines.append(f"    UPDATE nexent.model_record_t")
            lines.append(f"       SET context_window_tokens = COALESCE(context_window_tokens,")
            lines.append(f"           GREATEST({_sql_int(ctx)}, COALESCE(max_output_tokens, 0) + 1)),")
            lines.append(f"           max_output_tokens = COALESCE(max_output_tokens,")
            lines.append(f"           LEAST({_sql_int(mout)}, COALESCE(context_window_tokens, {_sql_int(ctx)}) - 1)),")
            lines.append(f"           default_output_reserve_tokens = COALESCE(default_output_reserve_tokens,")
            lines.append(f"           LEAST({_sql_int(reserve)}, COALESCE(max_output_tokens, {_sql_int(mout)}))),")
            lines.append(f"           capacity_source = COALESCE(capacity_source, 'profile'),")
            lines.append(f"           capability_profile_version = COALESCE(capability_profile_version, '{version}')")
            lines.append(f"     WHERE LOWER(model_factory) = '{_sql_str(provider.lower())}'")
            lines.append(f"       AND model_name = '{escaped_model}'")
            lines.append(f"       AND delete_flag = 'N'")
            lines.append(f"       AND (context_window_tokens IS NULL OR max_output_tokens IS NULL);")
            lines.append(f"    GET DIAGNOSTICS v_updated = ROW_COUNT;")
            lines.append(f"    v_total := v_total + v_updated;")
            lines.append("")

    lines.append("    RAISE NOTICE 'Catalog backfill: % row(s) updated', v_total;")
    lines.append("END $$;")
    lines.append("")

    # Phase 2: safe defaults for remaining bare rows
    lines.append("-- ============================================================")
    lines.append("-- Phase 2: Safe defaults for remaining bare LLM/VLM rows")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("BEGIN")
    lines.append("    UPDATE nexent.model_record_t")
    lines.append(f"       SET context_window_tokens = COALESCE(context_window_tokens,")
    lines.append(f"           GREATEST({_sql_int(DEFAULT_CONTEXT_WINDOW)}, COALESCE(max_output_tokens, 0) + 1)),")
    lines.append(f"           max_output_tokens = COALESCE(max_output_tokens,")
    lines.append(f"           LEAST({_sql_int(DEFAULT_MAX_OUTPUT)}, COALESCE(context_window_tokens, {_sql_int(DEFAULT_CONTEXT_WINDOW)}) - 1)),")
    lines.append(f"           default_output_reserve_tokens = COALESCE(default_output_reserve_tokens,")
    lines.append(f"           LEAST({_sql_int(DEFAULT_RESERVE)}, COALESCE(max_output_tokens, {_sql_int(DEFAULT_MAX_OUTPUT)}))),")
    lines.append(f"           capacity_source = COALESCE(capacity_source, 'default')")
    lines.append("     WHERE delete_flag = 'N'")
    lines.append("       AND COALESCE(model_type, 'llm') IN ('llm', 'vlm')")
    lines.append("       AND (context_window_tokens IS NULL OR max_output_tokens IS NULL);")
    lines.append("")
    lines.append("    GET DIAGNOSTICS v_updated = ROW_COUNT;")
    lines.append("    RAISE NOTICE 'Safe defaults: % LLM/VLM row(s) backfilled', v_updated;")
    lines.append("END $$;")
    lines.append("")

    # Phase 3: reconcile max_tokens
    lines.append("-- ============================================================")
    lines.append("-- Phase 3: Reconcile legacy max_tokens with max_output_tokens")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("BEGIN")
    lines.append("    UPDATE nexent.model_record_t")
    lines.append("       SET max_tokens = max_output_tokens")
    lines.append("     WHERE delete_flag = 'N'")
    lines.append("       AND max_output_tokens IS NOT NULL")
    lines.append("       AND COALESCE(max_tokens, -1) <> max_output_tokens")
    lines.append("       AND COALESCE(model_type, '') NOT IN ('embedding', 'multi_embedding');")
    lines.append("")
    lines.append("    GET DIAGNOSTICS v_updated = ROW_COUNT;")
    lines.append("    RAISE NOTICE 'max_tokens reconcile: % row(s) updated', v_updated;")
    lines.append("END $$;")
    lines.append("")

    # Phase 4: clamp reserve to max_output
    lines.append("-- ============================================================")
    lines.append("-- Phase 4: Clamp default_output_reserve_tokens to max_output_tokens")
    lines.append("-- ============================================================")
    lines.append("")
    lines.append("DO $$")
    lines.append("DECLARE")
    lines.append("    v_updated INTEGER := 0;")
    lines.append("BEGIN")
    lines.append("    UPDATE nexent.model_record_t")
    lines.append("       SET default_output_reserve_tokens = max_output_tokens")
    lines.append("     WHERE delete_flag = 'N'")
    lines.append("       AND default_output_reserve_tokens IS NOT NULL")
    lines.append("       AND max_output_tokens IS NOT NULL")
    lines.append("       AND default_output_reserve_tokens > max_output_tokens;")
    lines.append("")
    lines.append("    GET DIAGNOSTICS v_updated = ROW_COUNT;")
    lines.append("    RAISE NOTICE 'reserve clamp: % row(s) updated', v_updated;")
    lines.append("END $$;")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
