apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexent-elasticsearch-pv
  labels:
    type: local
    app: nexent-elasticsearch
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  storageClassName: hostpath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.global.dataDir }}/nexent-elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexent-elasticsearch
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: nexent-elasticsearch-pv
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexent-postgresql-pv
  labels:
    type: local
    app: nexent-postgresql
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.global.dataDir }}/nexent-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexent-postgresql
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: nexent-postgresql-pv
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexent-redis-pv
  labels:
    type: local
    app: nexent-redis
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  storageClassName: hostpath
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.global.dataDir }}/nexent-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexent-redis
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: nexent-redis-pv
  storageClassName: hostpath
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexent-minio-pv
  labels:
    type: local
    app: nexent-minio
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  storageClassName: hostpath
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.global.dataDir }}/nexent-minio
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexent-minio
  namespace: {{ .Values.global.namespace }}
  annotations:
    "helm.sh/hook-weight": "-3"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: nexent-minio-pv
  storageClassName: hostpath
