name: Docker Build Web Images

concurrency:
  group: docker-build-web-dev-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    paths:
      - 'frontend/**'
      - 'make/web/**'
  push:
    branches: [develop]
    paths:
      - 'frontend/**'
      - 'make/web/**'

jobs:
  build-web-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        run: |
          if ! docker buildx inspect nexent_builder > /dev/null 2>&1; then
            docker buildx create --name nexent_builder --use
          else
            docker buildx use nexent_builder
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build web image (amd64) and load locally
        run: |
          docker buildx build --platform linux/amd64 -t nexent/nexent-web:dev-amd64 --load -f make/web/Dockerfile .

  build-web-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        run: |
          if ! docker buildx inspect nexent_builder > /dev/null 2>&1; then
            docker buildx create --name nexent_builder --use
          else
            docker buildx use nexent_builder
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build web image (arm64) and load locally
        run: |
          docker buildx build --platform linux/arm64 -t nexent/nexent-web:dev-arm64 --load -f make/web/Dockerfile .