name: Docker Build Main Images

concurrency:
  group: docker-build-main-dev-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    paths:
      - 'backend/**'
      - 'sdk/**'
      - 'make/main/**'
  push:
    branches: [develop]
    paths:
      - 'backend/**'
      - 'sdk/**'
      - 'make/main/**'

jobs:
  build-main-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        run: |
          if ! docker buildx inspect nexent_builder > /dev/null 2>&1; then
            docker buildx create --name nexent_builder --use
          else
            docker buildx use nexent_builder
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build main image (amd64) and load locally
        run: |
          docker buildx build --platform linux/amd64 -t nexent/nexent:dev-amd64 --load -f make/main/Dockerfile .

  build-main-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        run: |
          if ! docker buildx inspect nexent_builder > /dev/null 2>&1; then
            docker buildx create --name nexent_builder --use
          else
            docker buildx use nexent_builder
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build main image (arm64) and load locally
        run: |
          docker buildx build --platform linux/arm64 -t nexent/nexent:dev-arm64 --load -f make/main/Dockerfile .