name: Docker Build Terminal Images

concurrency:
  group: docker-build-terminal-dev-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    branches: [develop]
    paths:
      - 'make/terminal/**'
      - '.github/workflows/**'
  push:
    branches: [develop]
    paths:
      - 'make/terminal/**'
      - '.github/workflows/**'

jobs:
  build-terminal-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build terminal image (amd64) and load locally
        run: |
          docker build --platform linux/amd64 -t nexent/nexent-ubuntu-terminal:dev-amd64 -f make/terminal/Dockerfile .

  build-terminal-arm64:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build terminal image (arm64) and load locally
        run: |
          docker build --platform linux/arm64 -t nexent/nexent-ubuntu-terminal:dev-arm64 -f make/terminal/Dockerfile .